### ISSUE TITLE
allow users to signin without google auth

### ISSUE THREAD

**Issue by ddwag1** [calify-io/calify#100]
email, facebook, twitter, github.
@maxletourneur thoughts?

**Comment by maxletourneur** [comment]
I think email/password would be nice facebook maybe, twitter/github I wouldn't bother

**Comment by ddwag1** [comment]
I mean only if we could find a drag-n-drop component to do it

**Comment by ddwag1** [comment]
doesnt polyfire allow for all of those?
In firebase go to Authentication -> Sign-in Method

**Comment by maxletourneur** [comment]
They are all easy to integrate I'm not it's useful

**Comment by maxletourneur** [comment]
For twitter and github
